### ISSUE TITLE
[Question] What's the purpose of VersionedTextDocumentIdentifier

### ISSUE THREAD

**Issue by svenefftinge** [Microsoft/vscode-languageserver-protocol#10]
I understood that when a document is opened it gets an initial version number, and subsequent calls to didChange get incremented version numbers.

As no other operations refer to this version, I am wondering what the purpose of it is.

I can imagine that when using the protocol with an HTTP server (REST) there might be missing messages or jeopardised orderings. But than all references should use the version, too.

**Comment by dbaeumer** [comment]
The purpose is more when applying changes back to a document. Consider the following use case:

- language server receives a change event and records the version number
- does some error checking and computes auto fixes for detected errors
- sends the auto fixes (including the version number they got computed on back to the client)
- the client can now check whether the document is still in that version and then apply the edits. If not it simply waits until new fixes have been computed (trigger by new change events)

Without the version number a client can't determine if edits to a document computed by a server are still valid or not.

**Comment by svenefftinge** [comment]
Ok, thanks I understand. 
Auto fixes are not yet defined but planned for the future, right?

I wonder if it would be a good idea to always use a version when referencing text documents, since otherwise e.g. a completion request would imply that the version on the server is the same as on the client, which can be guaranteed in a synchronous setting, but not when using e.g. an http server to process requests in parallel.

**Comment by dbaeumer** [comment]
I see the problem with the parallel request processing model. Currently the protocol assumes that requests/notifications are processed on the server in the same order as send from the client. I actually don't know if we should add the parallel processing to the protocol or let it be up to the server implementation to decide whether stuff can be executed in parallel or not.

Regarding quick fix: they are in, but named code actions. Because code actions can do more than fixing problems. You want to have a look at https://github.com/Microsoft/vscode-eslint to see how that works

**Comment by dbaeumer** [comment]
I opened #12 to at least document the current behavior.
